apiVersion: v2
name: fylr
description: Deploy fylr to your Kubernetes cluster

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

version: 1.1.180

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v6.26.0"

maintainers:
  - name: programmfabrik
    email: support@programmfabrik.de
    url: https://programmfabrik.de

dependencies:
  # Beware: use helm dependency update (in charts/fylr) to download them to charts/fylr/charts

  # https://github.com/minio/minio/tree/master/helm/minio
  - name: minio
    version: 4.0.14
    repository: https://charts.min.io/
    condition: minio.enabled
  # https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha
  - name: postgresql-ha
    version: 16.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql-ha.enabled
  # https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch
  - name: elasticsearch
    version: 19.21.2
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  # https://github.com/bitnami/charts/tree/main/bitnami/opensearch
  - name: opensearch
    version: 1.2.6
    repository: https://charts.bitnami.com/bitnami
    condition: opensearch.enabled
  # https://programmfabrik.github.io/fylr-helm/charts/execserver/
  - name: execserver
    version: 0.1.84
    repository: https://programmfabrik.github.io/fylr-helm
    condition: execserver.enabled
  # https://github.com/bitnami/charts/tree/master/bitnami/postgresql
  - name: postgresql
    version: 16.7.27
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
