apiVersion: v2
name: fylr
description: Deploy fylr to your Kubernetes cluster

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.5

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v6.1.0-beta.8"

maintainers:
  - name: Klaus Thorn
    email: klaus.thorn@programmfabrik.de
    url: https://github.com/KlausThornProgrammfabrik

dependencies:
  # https://github.com/minio/minio/tree/master/helm/minio
  - name: minio
    version: 4.0.14
    repository: https://charts.min.io/
    condition: minio.enabled
  # https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha
  - name: postgresql-ha
    version: 10.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql-ha.enabled
  # https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch
  - name: elasticsearch
    version: 19.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  # https://programmfabrik.github.io/fylr-helm/charts/execserver/
  - name: execserver
    version: 0.1.1
    repository: https://programmfabrik.github.io/fylr-helm
    condition: execserver.enabled
