# -- (object) The image to use for the container
image:
  # -- (string) Docker image repository

  repository: docker.fylr.io/fylr/fylr
  pullPolicy: Always
  # -- (string) Overrides the image tag whose default is the chart appVersion.
  tag: "main"

podAnnotations:
  created-at: "2024-04-1810:19:57"
  updated-at: ""
strategy:
  rollingUpdate: null
  type: Recreate
resources: 
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: "0.2"
    memory: 512Mi
replicaCount: 1
ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  hosts:
  - host: fylr-test.flux.programmfabrik.de
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - secretName: fylr-test-tls
    hosts:
      - fylr-test.flux.programmfabrik.de
fylr:
  allowPurge: true
  logger:
    level: info
  externalURL: "https://fylr-test.flux.programmfabrik.de"

  license: |
    {
          "created_at": "2023-06-15T12:45:13+02:00",
          "key": "30DE9B79-4CD5-4934-AC18-910B1746B106",
          "issuer": "Programmfabrik GmbH",
          "holder": "Programmfabrik",
          "type": "buy",
          "edition": "organization",
          "valid": {
              "from": null,
              "to": null
          },
          "capabilities": {
              "read_only": false,
              "mobile_app": true,
              "ci_hub": true,
              "auth": true
          },
          "domains": [
              "*.fylr.dev",
              "*.fylr.cloud"
          ],
          "signature": "y74XzA/DjpuHhb1ZBc3zDHA6N4qeioVstPtmOu6TwLC65odcsLLdXl7deE9gcnE1QZxNkS7Jn8BO\nn/qn3mTTlZgYLSB07tLVtrSscK8OVeZVfDMUGCoOmurTpYPUgkR5fxJKPGVgLDLp6IWZSl8LRVww\n3KEhjjzdIYatmc5pEhoQ7acBKGA7D7L9lqW3N2fxALtR/KNU5QBljOhwequJNGthyvCVe6z2+EEP\nFlBeoJv5/wlKghX0zlSDXFlv1pqeBuSB1RAP6VpO90WfINXz02xWeTEJ+Z7vX89iEzMo28YzxsUN\nkoD7c8fAu3YDf7DUtjhLPy8FeCXeyqgVk64gYw=="
    }
        
  persistent:
    # -- (object) To make the /tmp fylr dir persistent across redeploy
    tmp:
      # -- (bool) Wether to enable persistance for tmp dir or not
      enabled: false
      accessModes: ["ReadWriteMany"]
       # -- (string) storageClass is the storage class of the file system. Check your kubernetes infrastructure for the available storage classes.
      storageClass: "longhorn"
      # -- (string) size is the size of the disk to be claimed and used by fylr tmp dir.
      size: "30Gi"
    webDAVHotfolder:
      # -- (bool) Wether to enable persistance for tmp dir or not
      enabled: false
      accessModes: ["ReadWriteMany"]
       # -- (string) storageClass is the storage class of the file system. Check your kubernetes infrastructure for the available storage classes.
      storageClass: "longhorn"
      # -- (string) size is the size of the disk to be claimed and used by fylr tmp dir.
      size: "30Gi"    
    defaults:
      originals: "s3"
      versions: "s3"
      backups: "disk1"
    definitions:
      disk1:
        kind: disk
        allowPurge: false
        disk:
          storageClass: "longhorn"
          accessModes: ["ReadWriteMany"]
          size: 10Gi
      s3:
        kind: s3
        # This is a dangerous setting and should be used for development purposes only.
        allowPurge: true
        # -- (object) s3 is the configuration for the s3 storage.
        s3:
          path: "fylr-test"
          bucket: "pf-fylr-demo-cluster-bucket"
          endpoint: "https://s3.de.io.cloud.ovh.net/"
          accessKey: "5d5f548d9b1c44308bd630963f85c7e9"
          secretKey: "1992b4797eba430ab130eef1bd0e800c"
          region: "de"
          useSSL: true
          # For public s3 providers like AWS, this should be set to true.
          allowRedirect: false

minio:
  enabled: false
postgresql-ha:
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain
    whenDeleted: Retain

  enabled: false
  postgresql:
    livenessProbe:
      enabled: false
    replicaCount: 1
  pgpool:
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
postgresql:
  enabled: true
  postgresql:
    auth:
      username: "fylr"
      password: "fylr"
      database: "fylr"
  auth:
    username: "fylr"
    ## @param auth.password Password for the custom user to create. Ignored if `auth.existingSecret` is provided
    ##
    password: "fylr"
    ## @param auth.database Name for a custom database to create
    ##
    database: "fylr"
  primary:
    name: master
    persistence:
      storageClass: "longhorn"
      volumeName: "data"


elasticsearch:
  enabled: false
  master:
    masterOnly: false
    replicaCount: 1
    persistence:
      storageClass: longhorn
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1000Mi
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0

  metrics:
    enabled: false
opensearch:
  enabled: true
  master:
    masterOnly: false
    heapSize: 1024m
    replicaCount: 1
    persistence:
      storageClass: longhorn
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0

  metrics:
    enabled: false
execserver:
  enabled: true
  # -- The image to use for the execserver
  image:
    # -- The image repository
    repository: docker.fylr.io/fylr/fylr
    # -- The image pull policy. See https://kubernetes.io/docs/concepts/containers/images/#updating-images
    pullPolicy: IfNotPresent
    # -- The image tag
    # Overrides the image tag whose default value is the appVersion of the chart.
    #tag: "v6.8.2"
  # -- Whether to configure monitoring for the application
  persistent:
    # -- (object) To make the /tmp fylr dir persistent across redeploy
    tmp:
      # -- (bool) Wether to enable persistance for tmp dir or not
      enabled: true
      accessModes: ["ReadWriteOnce"]
        # -- (string) storageClass is the storage class of the file system. Check your kubernetes infrastructure for the available storage classes.
      storageClass: "longhorn"
      # -- (string) size is the size of the disk to be claimed and used by fylr tmp dir.
      size: "20Gi"