apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.db.name" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ if (index .Values "postgresql-ha" "enabled") }}
  driver: "postgres"
  dsn: 'postgres://{{ index .Values "postgresql-ha" "postgresql" "username" }}@{{ .Release.Name }}-postgresql-ha-pgpool.{{ .Release.Namespace }}.svc:5432/{{ index .Values "postgresql-ha" "postgresql" "database" }}?sslmode=disable&application_name=fylr&password={{ index .Values "postgresql-ha" "postgresql" "password" }}'
  {{ else }}
  driver: {{ .Values.fylr.db.driver | quote }}
  {{ $baseDSN := printf "postgres://%s@%s:%v/%s?sslmode=%s&application_name=fylr&password=%s" .Values.fylr.db.postgres.user .Values.fylr.db.postgres.host .Values.fylr.db.postgres.port .Values.fylr.db.postgres.database .Values.fylr.db.postgres.sslmode .Values.fylr.db.postgres.password }}
  # range options and append to baseDSN
  {{- range $key, $value := .Values.fylr.db.postgres.options }}
  {{- $baseDSN = printf "%s&%s=%s" $baseDSN $key $value }}
  {{- end }}
  dsn: {{ $baseDSN}}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.elastic.name" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ if .Values.elasticsearch.enabled }}
  username: ""
  password: ""
  hosts: '["http://{{ .Release.Name }}-elasticsearch.{{ .Release.Namespace }}.svc:9200"]'
  {{ else }}
  username: {{ .Values.fylr.elastic.username | quote }}
  password: {{ .Values.fylr.elastic.password | quote }}
  hosts: {{ .Values.fylr.elastic.addresses | toJson | quote }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.oauth2.name" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ $placeholderuser := "placeholder" }}
  {{ $plaintextpassword := (randAlphaNum 32) }}
  {{/* generate the bcrypt hash and remove the username: prefix from the string */}}
  {{ $oauth2_webapp_client_secret := trimPrefix (printf "%s:" $placeholderuser) (htpasswd $placeholderuser $plaintextpassword) }}
  oauth2ServerClientSecret: {{ $oauth2_webapp_client_secret | quote }}
  oauth2WebappClientSecret: {{ $plaintextpassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.utils" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
type: Opaque
stringData:
  encryptionKey: {{ randAlphaNum 32 | quote }}
  signinSecret: {{ randAlphaNum 32 | quote }}
