apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.db.name" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ if (index .Values "postgresql-ha" "enabled") }}
  driver: "postgres"
  dsn: 'postgres://{{ index .Values "postgresql-ha" "postgresql" "username" }}@{{ .Release.Name }}-postgresql-ha-pgpool.{{ .Release.Namespace }}.svc:5432/{{ index .Values "postgresql-ha" "postgresql" "database" }}?sslmode=disable&application_name=fylr&password={{ index .Values "postgresql-ha" "postgresql" "password" }}'
  {{ else }}
  driver: {{ .Values.fylr.db.driver | quote }}
  {{ $baseDSN := printf "postgres://%s@%s:%v/%s?sslmode=%s&application_name=fylr&password=%s" .Values.fylr.db.postgres.user .Values.fylr.db.postgres.host .Values.fylr.db.postgres.port .Values.fylr.db.postgres.database .Values.fylr.db.postgres.sslmode .Values.fylr.db.postgres.password }}
  # range options and append to baseDSN
  {{- range $key, $value := .Values.fylr.db.postgres.options }}
  {{- $baseDSN = printf "%s&%s=%s" $baseDSN $key $value }}
  {{- end }}
  dsn: {{ $baseDSN}}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.elastic.name" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ if .Values.elasticsearch.enabled }}
  username: ""
  password: ""
  hosts: '["http://{{ .Release.Name }}-elasticsearch.{{ .Release.Namespace }}.svc:9200"]'
  {{ else }}
  username: {{ .Values.fylr.elastic.username | quote }}
  password: {{ .Values.fylr.elastic.password | quote }}
  hosts: {{ .Values.fylr.elastic.addresses | toJson | quote }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.oauth2.name" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{ $placeholderuser := "placeholder" }}
  {{ $plaintextpassword := (randAlphaNum 32) }}
  {{/* generate the bcrypt hash and remove the username: prefix from the string */}}
  {{ $oauth2_webapp_client_secret := trimPrefix (printf "%s:" $placeholderuser) (htpasswd $placeholderuser $plaintextpassword) }}
  oauth2ServerClientSecret: {{ $oauth2_webapp_client_secret | quote }}
  oauth2WebappClientSecret: {{ $plaintextpassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.utils" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  encryptionKey: {{ randAlphaNum 32 | quote }}
  signinSecret: {{ randAlphaNum 32 | quote }}
{{ if .Values.fylr.db.init.config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.init.name" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
type: Opaque
stringData:
  fylr.init.yaml: |
    {{ toYaml .Values.fylr.db.init.config | nindent 6 }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.storage.name" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ $persistent := .Values.fylr.persistent }}
  {{- range $key, $val := $persistent.definitions -}}
  {{- if or (eq $key $persistent.defaults.originals) (eq $key $persistent.defaults.versions) (eq $key $persistent.defaults.backups) -}}

  {{/* check if it is a disk */}}
  {{- if eq $val.kind "disk" -}}

  {{- if eq $key $persistent.defaults.originals -}}
  {{- $name := "originals" -}}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $name }}_ALLOW_PURGE: {{ $val.allowPurge | default "false" | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $name }}_ALLOW_REDIRECT: "false"
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $name }}_KIND: "file"
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $name }}_CONFIG_FILE_DIR: "/fylr/files/assets/originals"
  {{/* end if for key is originals */}}
  {{- end -}}

  {{- if eq $key $persistent.defaults.versions -}}
  {{- $name := "versions" -}}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $name }}_ALLOW_PURGE: {{ $val.allowPurge | default "false" | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $name }}_ALLOW_REDIRECT: "false"
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $name }}_KIND: "file"
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $name }}_CONFIG_FILE_DIR: "/fylr/files/assets/versions"
  {{/* end if for key is originals */}}
  {{- end -}}

  {{- if eq $key $persistent.defaults.backups -}}
  {{- $name := "backups" -}}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $name }}_ALLOW_PURGE: {{ $val.allowPurge | default "false" | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $name }}_ALLOW_REDIRECT: "false"
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $name }}_KIND: "file"
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $name }}_CONFIG_FILE_DIR: "/fylr/files/backups"
  {{/* end if for key is originals */}}
  {{- end -}}

  {{/* check if the defined config is kind s3*/}}
  {{- else if eq $val.kind "s3" -}}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $key }}_CONFIG_S3_ENDPOINT: {{ $val.s3.endpoint | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $key }}_CONFIG_S3_ACCESSKEY: {{ $val.s3.accessKey | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $key }}_CONFIG_S3_SECRETKEY: {{ $val.s3.secretKey | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $key }}_CONFIG_S3_REGION: {{ $val.s3.region | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $key }}_CONFIG_S3_BUCKET: {{ $val.s3.bucket | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $key }}_CONFIG_S3_SSL: {{ $val.s3.useSSL | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $key }}_KIND: "s3"
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $key }}_PREFIX: {{ $val.s3.path | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $key }}_ALLOW_PURGE: {{ $val.allowPurge | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $key }}_ALLOW_REDIRECT: {{ $val.s3.allowRedirect | quote }}
  {{- else -}}
  {{/* fail if kind is not s3 or disk */}}
  {{- fail "Invalid Persistent Storage Kind. Supported values are 's3' and 'disk'." -}}
  {{/* end if is kind disk */}}
  {{- end -}}

  {{/* end if key is one of originals, versions, backups */}}
  {{- end -}}
  {{/* end range */}}
  {{- end -}}
