apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.db.name" . }}
type: Opaque
data:
  driver: {{ .Values.db.driver | b64enc | quote }}
  dsn: {{ .Values.db.dsn | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.elastic.name" . }}
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fylr.secret.s3.name" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.fylr.db.init.locations }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $value.name | upper }}_CONFIG_S3_ENDPOINT: {{ $value.config.s3.endpoint | b64enc | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $value.name | upper }}_CONFIG_S3_ACCESSKEY: {{ $value.config.s3.accessKey | b64enc | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $value.name | upper }}_CONFIG_S3_SECRETKEY: {{ $value.config.s3.secretKey | b64enc | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $value.name | upper }}_CONFIG_S3_REGION: {{ $value.config.s3.region | b64enc | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $value.name | upper }}_CONFIG_S3_BUCKET: {{ $value.config.s3.bucket | b64enc | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $value.name | upper }}_CONFIG_S3_SSL: {{ if $value.config.s3.ssl }}{{ print "on" | b64enc | quote }}{{ else }}{{ print "off" | b64enc | quote }}{{ end }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $value.name | upper }}_KIND: {{ print "s3" | b64enc | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $value.name | upper }}_PREFIX: {{ $value.pathPrefix | b64enc | quote }}
  CFG_FYLR_DB_INIT_LOCATIONS_{{ $value.name | upper }}_ALLOW_PURGE: {{ $value.allowPurge | b64enc | quote }}
  {{- end }}
