---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fylr.service.webapp.name" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.webapp.type }}
  ports:
    - port: {{ .Values.service.webapp.port }}
      targetPort: api
      protocol: TCP
      name: webapp
  selector:
    {{- include "fylr.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fylr.service.api.name" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "fylr.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fylr.service.backend.name" . }}
  labels:
    {{- include "fylr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: backend
      protocol: TCP
      name: backend
  selector:
    {{- include "fylr.selectorLabels" . | nindent 4 }}