kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "execserver.fullname" . }}
data:
  fylr.yml: |
    fylr+:
      name: {{ include "execserver.fullname" . }}
      debug+:
        skipTerms: false
      logger+:
        # Set to "json" or "console". Default: "console"
        format: "console"
        # Set zerolog log level: trace, debug, info, warn, error, fatal, panic
        # default to "info".
        level: {{ default "info" .Values.fylr.logger.level }}
        # timeFormat is the Go representation to format the time in the log output.
        # zerolog's time keeping resolution is always set to milliseconds by FYLR.
        # Use "", "UNIXMS" or "UNIXMICRO" to output a unix timestamp (json format only).
        # Defaults to ""
        timeFormat: ""
        # turn off color for zerolog's underlying ConsoleWriter
        # format: "console" only.
        noColor: false
        # add hostname to log output
        addHostname: true
      resources: "/fylr/files/resources"
      services+:
        api: {}
        backend: {}
        webapp: {}
        execserver+:
          addr: :7070
          tempDir: /tmp/fylr
          waitgroups:
            {{- range $k, $v := .Values.fylr.execserver.waitGroups }}
            {{ $k }}:
              processes: {{ $v -}}
            {{ end }}

