apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "execserver.fullname" . }}
  labels:
    {{- include "execserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "execserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # trigger updates to the pod when the configmap has changed
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- range $k, $v := .Values.podAnnotations }}
        {{ $k | nindent 8 }}: {{ $v }}
        {{- end }}
      labels:
        {{- include "execserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "execserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7070
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /healthz
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /healthz
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /fylr/config
              name: fylr-config
      volumes:
        - name: "fylr-config"
          configMap:
            name: {{ include "execserver.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
