name: Pull Request automations

on:
  pull_request:
  pull_request_target:

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  security-events: read
  statuses: read

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add size label
        uses: "pascalgn/size-label-action@v0.4.3"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORED: ".gitignore\n*.md\n*.MD\n*.json\n*.sql\n*.yaml\n*.yml\n.dockerignore\ngo.mod\ngo.sum\nLICENSE"
        with:
          sizes: >
            {
              "0": "XS",
              "100": "S",
              "500": "M",
              "1000": "L",
              "1500": "XL",
              "2500": "XXL"
            }

  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}